import "./bootstrap.min.css";
import 'react-toastify/dist/ReactToastify.css';
import "../public/static/css/style.css";
import "./globals.css";
import type { Metadata } from "next";
import Navigation from "@/components/Navigation";
import Provider from "@/components/Provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  session,
}: {
  children: React.ReactNode;
  session: any;
}) {
  return (
    <html lang="en">
      <body >
        <Provider session={session}>
          
          <main className="content-container">{children}</main>
        </Provider>
        <script src="/static/js/bootstrap.bundle.min.js"></script>
      </body>
    </html>
  );
}
